### ISSUE TITLE
Ingame tracker

### ISSUE THREAD

**Issue by Berserker66** [Daivuk/ArchipelagoSubnauticaModSrc#7]
It would be quite helpful, especially in the early learning stages of the randomizer, to have some kind of ingame tracking.

A full map tracker would be great, something similar to https://www.nexusmods.com/subnautica/mods/12
A simpler method might be a special compass that points to the nearest not yet checked location, similar to a scanner room.

**Comment by Daivuk** [comment]
Closing this, a tracker is being built by Lurch9229
![image](https://user-images.githubusercontent.com/2482827/149632735-5177072a-e593-489e-a942-ceebfb6a6420.png)
